### ISSUE TITLE
Network stats update 

### ISSUE THREAD

**Issue by heatedlime** [helium/network-explorer#78]
Not an issue, but I think adding the below to the networks stats page would be cool to see:

- Tokens emitted last epoch for all subDAOs and helium DAO. Kudos if you can even break that down even further into what buckets those are being distributed from (I.e. amount of MOBILE rewarded for POC, data, etc). 

- Max supply of HNT and DNTs. As more than 1,643 HNT is burned in one epoch, this will lower the overall max supply, and I think it’s interesting to see this happen in real time.

**Comment by Siegfried-B** [comment]
I second that, particularly the max supply estimates. Would also be useful to (be able) to communicate  up to date max supplies (or at least upper thresholds) to sites like Coinmarketcap and Coingecko so that they can show correct max supplies numbers and correct fully diluted market caps to their users.

Max supplies shrinking over time applies to IOT and MOBILE, too - as there are burns whenever subDAO tokens are redeemed for HNT at the treasuries.

**Comment by mbthiery** [comment]
Noted. Adding to my to-do list.

**Comment by mbthiery** [comment]
@heatedlime and @Siegfried-B PR is up. Not sure if you automatically got notifications from the above activity.

**Comment by heatedlime** [comment]
Looks great!
